'use strict';
const E=SensorShift,$=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');
const KEY='sensor-shift-v1-history';let history=[];try{const parsed=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(parsed))history=parsed.filter(h=>Number.isInteger(h.angle)&&Math.abs(h.angle)<=45&&['success','collision','timeout'].includes(h.state)).slice(0,8)}catch{}
let s=E.create(0),running=false,finished=false,oldPath=null,lastFrame=0,acc=0,flash=0,frameId=0; s.state='ready';
const fmt=a=>(a>0?'+':'')+a+'°';
function save(){try{localStorage.setItem(KEY,JSON.stringify(history))}catch{}}
function historyUI(){$('history').replaceChildren();if(!history.length){const li=document.createElement('li');li.textContent='まだ試行なし。まずは再生して観察しよう';$('history').append(li)}history.forEach((h,i)=>{const li=document.createElement('li'),b=document.createElement('button'),r=document.createElement('span'),m=document.createElement('span');b.textContent=fmt(h.angle);b.disabled=running;b.onclick=()=>{setAngle(h.angle)};r.className='result';r.textContent=h.state==='success'?'出口に到達':h.state==='collision'?'壁に衝突':'時間切れ';m.className='meta';m.textContent=`${Number(h.time).toFixed(1)}秒 / ${h.turns}旋回`;li.append(b,r,m);$('history').append(li)})}
function lock(on){['angle','minus','plus'].forEach(id=>$(id).disabled=on);historyUI()}
function reset(){cancelAnimationFrame(frameId);if(finished)oldPath=s.path.map(p=>({...p}));running=false;finished=false;s=E.create(Number($('angle').value));s.state='ready';acc=0;flash=0;$('play').textContent='▶ 再生';$('state').textContent='角度を決めて、再生';$('feedback').textContent='青い線がセンサー。角度を変えると、壁を見るタイミングが変わる';lock(false);draw()}
function setAngle(a){if(running)return;$('angle').value=Math.max(-45,Math.min(45,a));$('angleValue').textContent=fmt(Number($('angle').value));reset()}
$('angle').oninput=()=>setAngle(Number($('angle').value));$('minus').onclick=()=>setAngle(Number($('angle').value)-1);$('plus').onclick=()=>setAngle(Number($('angle').value)+1);$('reset').onclick=reset;
$('clear').onclick=()=>{history=[];save();historyUI()};
$('play').onclick=()=>{if(running){running=false;cancelAnimationFrame(frameId);$('play').textContent='▶ 続ける';$('state').textContent='一時停止';return}if(finished)reset();s.state='running';running=true;lastFrame=0;lock(true);$('play').textContent='Ⅱ 一時停止';$('state').textContent='観察中';$('feedback').textContent='壁を検知した瞬間に注目。赤い丸が旋回した場所です';frameId=requestAnimationFrame(frame)};
function done(){running=false;finished=true;history.unshift({angle:s.angle,state:s.state,time:s.time,turns:s.turns});history=history.slice(0,8);save();lock(false);$('play').textContent='▶ もう一度';const success=s.state==='success';$('state').textContent=success?'✓ 出口に到達！':s.state==='collision'?'× 壁に衝突':'↺ 時間切れ';$('feedback').textContent=success?'成功！ 1°戻しても通れる？ どこまでずらせば避けられるか、境界を探そう':s.state==='collision'?'体が壁に触れた。曲がった場所は早すぎた？ 遅すぎた？ 角度を変えてもう一度':'12秒で終了。何度も曲がった場所を見て、角度を変えてみよう'}
function frame(t){if(!running)return;if(!lastFrame)lastFrame=t;acc+=Math.min((t-lastFrame)/1000,.1);lastFrame=t;while(acc>=1/120&&running){const turns=s.turns;E.step(s);acc-=1/120;if(s.turns>turns)flash=.5;flash=Math.max(0,flash-1/120);if(s.state!=='running')done()}draw();if(running)frameId=requestAnimationFrame(frame)}
function path(points,color,dash){if(!points||points.length<2)return;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash(dash||[]);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore()}
function draw(){const W=E.WORLD;ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,W.w,W.h);ctx.fillStyle='#edf4f8';ctx.fillRect(0,0,W.w,W.h);ctx.strokeStyle='#dce8ef';ctx.lineWidth=.5;for(let x=20;x<W.w;x+=20){ctx.beginPath();ctx.moveTo(x,8);ctx.lineTo(x,W.h-8);ctx.stroke()}for(let y=20;y<W.h;y+=20){ctx.beginPath();ctx.moveTo(8,y);ctx.lineTo(W.w-8,y);ctx.stroke()}
ctx.fillStyle='#d4ece5';ctx.fillRect(W.goal.x,W.goal.y,W.goal.w,W.goal.h);ctx.strokeStyle='#299574';ctx.lineWidth=2;ctx.strokeRect(W.goal.x,W.goal.y,W.goal.w,W.goal.h);ctx.fillStyle='#14745b';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText('出口',W.goal.x+W.goal.w/2,W.goal.y+22);
E.walls.forEach(r=>{ctx.fillStyle='#355367';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#527184';ctx.fillRect(r.x,r.y,r.w,3)});ctx.fillStyle='#7593a5';ctx.font='10px system-ui';ctx.textAlign='left';ctx.fillText('START →',35,178);ctx.fillText('障害物',102,301);path(oldPath,'#8caab9',[3,5]);path(s.path,'#1e87b5');
s.events.forEach(e=>{ctx.strokeStyle='#e16a4c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,5,0,Math.PI*2);ctx.stroke()});const q=E.sense(s);ctx.strokeStyle=q.hit?'#e75c45':'#22a4d8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(q.x,q.y,4,0,Math.PI*2);ctx.fill();
if(flash){ctx.fillStyle='#dc5a3d';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText('検知 → 右90°',s.x,s.y-25)}ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.heading);ctx.fillStyle=s.state==='collision'?'#fbd8cf':'white';ctx.strokeStyle='#173c55';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-11,-12,22,24,7);ctx.fill();ctx.stroke();ctx.fillStyle='#173c55';ctx.beginPath();ctx.roundRect(0,-8,9,16,4);ctx.fill();ctx.fillStyle='#54d1ef';ctx.fillRect(3,-5,3,3);ctx.fillRect(3,2,3,3);ctx.restore();$('timer').textContent=s.time.toFixed(1)+' s';$('sensor').textContent=q.hit?'● 壁まで '+q.distance.toFixed(0)+' / 100':'○ 検知なし / 範囲100';$('sensor').style.color=q.hit?'#c04430':'#086caa';$('turns').textContent='旋回 '+s.turns+' 回'}
historyUI();draw();
