const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../games/firebreak-keeper/engine.js'),routes=require('./firebreak-routes.cjs');
function act(s,crew,mode,x,y){s.selected=crew;s.mode=mode;return E.act(s,x,y);}
function clean(){const s=E.create();s.cells.forEach(c=>c.fire=0);return s;}
for(let i=0;i<3;i++)test(`mission ${i+1}: complete production-engine success route`,()=>{const s=E.create(i);for(const a of routes[i]){if(a==='next')assert.ok(E.advance(s));else assert.ok(act(s,...a),JSON.stringify(a));}assert.equal(s.status,'won');assert.equal(s.rescued,3);assert.equal(s.cells.filter(c=>c.fire).length,0);assert.equal(s.round,[3,4,6][i]);});
test('new games are independent and restart restores all state',()=>{let a=E.create(),b=E.create();a.crews[0].water=0;a.cells[0].kind='break';assert.equal(b.crews[0].water,3);assert.equal(b.cells[0].kind,'forest');assert.deepEqual(b,E.create());});
test('invalid mission inputs safely choose intro',()=>{assert.equal(E.create(NaN).mission,0);assert.equal(E.create(-1).mission,0);assert.equal(E.create(100).mission,2);});
test('two-step movement uses one action and cannot walk through fire',()=>{const s=E.create();assert.ok(act(s,0,'move',1,4));assert.equal(s.crews[0].ap,1);E.cell(s,1,3).fire=1;assert.ok(!E.reachable(s,s.crews[0]).some(c=>c.x===1&&c.y===2));});
test('invalid and repeated exhausted actions do not consume state',()=>{const s=E.create();assert.equal(act(s,0,'move',6,0),false);assert.equal(s.actions,0);assert.ok(act(s,0,'move',1,4));assert.ok(act(s,0,'rescue',1,3));for(let i=0;i<10;i++)assert.equal(act(s,0,'rescue',1,3),false);assert.equal(s.rescued,1);assert.equal(s.actions,2);assert.equal(s.crews[0].ap,0);});
test('saved residents cannot be counted twice on later turns',()=>{const s=E.create();act(s,0,'move',1,4);act(s,0,'rescue',1,3);E.advance(s);assert.equal(act(s,0,'rescue',1,3),false);assert.equal(s.rescued,1);});
test('water clears 3x3, spends exactly one, and works with an empty center',()=>{const s=clean();s.crews[0]={x:2,y:3,ap:2,water:3};E.cell(s,1,0).fire=1;E.cell(s,3,2).fire=1;assert.ok(act(s,0,'water',2,1));assert.equal(E.cell(s,1,0).fire,0);assert.equal(E.cell(s,3,2).fire,0);assert.equal(s.crews[0].water,2);assert.equal(E.cell(s,2,1).wet,2);});
test('empty water blocks action and cannot go negative',()=>{const s=E.create();s.crews[0]={x:2,y:2,ap:2,water:0};assert.equal(act(s,0,'water',2,0),false);assert.equal(s.crews[0].water,0);assert.equal(s.crews[0].ap,2);});
test('wet land blocks two spread events then dries',()=>{const s=clean();E.cell(s,2,0).fire=1;E.cell(s,2,1).wet=2;assert.ok(!E.forecast(s).includes(E.cell(s,2,1)));E.advance(s);assert.equal(E.cell(s,2,1).wet,1);assert.ok(!E.forecast(s).includes(E.cell(s,2,1)));E.advance(s);assert.equal(E.cell(s,2,1).wet,0);assert.equal(E.cell(s,2,1).fire,0);});
test('cut creates a permanent barrier without using water',()=>{const s=clean();s.crews[0]={x:2,y:2,ap:2,water:1};assert.ok(act(s,0,'cut',2,1));E.cell(s,2,0).fire=1;assert.equal(s.crews[0].water,1);assert.ok(!E.forecast(s).includes(E.cell(s,2,1)));E.advance(s);assert.equal(E.cell(s,2,1).kind,'break');});
test('cannot cut houses, wells, existing barriers, or burning forest',()=>{const s=E.create();s.crews[0]={x:1,y:3,ap:2,water:3};assert.equal(act(s,0,'cut',1,3),false);E.cell(s,1,2).fire=1;assert.equal(act(s,0,'cut',1,2),false);});
test('refill only at adjacent well and restores three charges',()=>{const s=E.create();s.crews[0].water=0;assert.ok(act(s,0,'refill',0,6));assert.equal(s.crews[0].water,3);assert.equal(act(s,0,'refill',0,6),false);assert.equal(act(s,1,'refill',0,6),false);});
test('forecast is unique, pure, and exactly matches new ignitions',()=>{const s=E.create(1);s.round=2;const before=JSON.stringify(s),f=E.forecast(s).map(c=>[c.x,c.y]);assert.equal(before,JSON.stringify(s));assert.equal(new Set(f.map(String)).size,f.length);E.advance(s);for(const[x,y]of f)assert.equal(E.cell(s,x,y).fire,1);});
test('even rounds spread sideways as well as downwind',()=>{const s=clean();E.cell(s,3,2).fire=1;assert.deepEqual(E.forecast(s).map(c=>[c.x,c.y]),[[3,3]]);s.round=2;assert.deepEqual(E.forecast(s).map(c=>[c.x,c.y]),[[3,3],[2,2],[4,2]]);});
test('fire naturally burns out after three spread events',()=>{const s=clean();E.cell(s,0,0).fire=1;E.advance(s);E.advance(s);E.advance(s);assert.equal(E.cell(s,0,0).fire,0);assert.equal(E.cell(s,0,0).kind,'ash');assert.ok(s.burned>=1);});
test('unrescued house ignition fails immediately',()=>{const s=clean();E.cell(s,1,2).fire=1;E.advance(s);assert.equal(s.status,'lost');assert.equal(E.cell(s,1,3).kind,'ruin');});
test('already rescued house ignition does not lose the mission',()=>{const s=clean();E.cell(s,1,3).saved=true;s.rescued=1;E.cell(s,1,2).fire=1;E.advance(s);assert.equal(s.status,'playing');});
test('crew in incoming fire safely retreats and loses one water',()=>{const s=clean();s.crews[0].x=2;s.crews[0].y=2;E.cell(s,2,1).fire=1;E.advance(s);assert.deepEqual(s.crews[0],{x:1,y:6,water:2,ap:2});});
test('time limit fails, terminal inputs are inert, retry is clean',()=>{const s=clean();s.round=E.missions[0].limit;E.advance(s);assert.equal(s.status,'lost');const before=JSON.stringify(s);assert.equal(E.advance(s),false);assert.equal(E.act(s,1,4),false);assert.equal(JSON.stringify(s),before);assert.equal(E.create().status,'playing');});
test('all residents rescued alone does not win while fire remains',()=>{const s=E.create();s.rescued=2;s.cells.filter(c=>c.kind==='house').slice(0,2).forEach(c=>c.saved=true);s.crews[0]={x:3,y:6,ap:2,water:3};act(s,0,'rescue',3,5);assert.equal(s.rescued,3);assert.equal(s.status,'playing');});
test('serializable undo snapshot restores full state including wind and resources',()=>{const s=E.create();const saved=JSON.stringify(s);act(s,0,'move',1,4);E.advance(s);assert.deepEqual(JSON.parse(saved),E.create());});
test('deterministic replay across repeated complete runs',()=>{function run(){const s=E.create(2);for(const a of routes[2])a==='next'?E.advance(s):act(s,...a);return s;}assert.deepEqual(run(),run());});
for(let id=0;id<3;id++)test(`mission ${id+1}: rescuing and waiting for entire forest to burn cannot win`,()=>{const s=E.create(id);act(s,0,'move',1,4);act(s,0,'rescue',1,3);act(s,1,'move',5,4);act(s,1,'rescue',5,3);E.advance(s);act(s,0,'move',2,5);act(s,0,'rescue',3,5);assert.equal(s.rescued,3);while(s.status==='playing')E.advance(s);assert.equal(s.status,'lost');assert.ok(s.burned>E.missions[id].burnLimit);});
test('burn limit permits exactly eight but fails nine before success',()=>{const s=clean();s.rescued=3;s.burned=8;E.advance(s);assert.equal(s.status,'won');const t=clean();t.rescued=3;t.burned=9;E.advance(t);assert.equal(t.status,'lost');});
test('crew retreat remains in the next-turn feedback',()=>{const s=clean();s.crews[0].x=2;s.crews[0].y=2;E.cell(s,2,1).fire=1;E.advance(s);assert.match(s.message,/退避/);});
