'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const E=require('../games/night-market/engine.js');
const {bestPlan}=require('./helpers/night-market-policy.cjs');
// Minimal DOM fixture, not a browser rendering/accessibility test.
function mount(){
 let state,focused=null,buttons=[],html='',listeners={},notice={textContent:''};
 const app={set innerHTML(value){html=value;buttons=[...value.matchAll(/<button\b([^>]*)>(.*?)<\/button>/gs)].map(m=>{const attrs=m[1];const b={dataset:{action:/data-action="([^"]*)"/.exec(attrs)[1]},disabled:/\sdisabled(?:\s|$)/.test(attrs),focus(){focused=b;},closest(){return b;}};const g=/data-good="([^"]*)"/.exec(attrs);if(g)b.dataset.good=g[1];return b;});},get innerHTML(){return html;},contains(b){return buttons.includes(b);},addEventListener(type,fn){listeners[type]=fn;},querySelector(selector){const a=/data-action="([^"]*)"/.exec(selector),g=/data-good="([^"]*)"/.exec(selector);return buttons.find(b=>!b.disabled&&(!selector.startsWith('.actions')||!['buy','remove'].includes(b.dataset.action))&&(!a||b.dataset.action===a[1])&&(!g||b.dataset.good===g[1]))||null;}};
 const engine={...E,create(...a){return state=E.create(...a);},act(...a){return state=E.act(...a);}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../games/night-market/game.js'),'utf8'),{window:{NightMarket:engine},document:{querySelector(s){return s==='#app'?app:notice;}},Date});
 return {get state(){return state;},get html(){return html;},get focused(){return focused;},notice,listeners,buttons:()=>buttons,click(type,good){const b=buttons.find(b=>b.dataset.action===type&&(good===undefined||Number(b.dataset.good)===good));assert.ok(b,`missing ${type}`);listeners.click({target:b});return b;}};
}
test('controller renders stock, changes counts, refunds and enforces disabled capacity',()=>{const u=mount();assert.equal(u.state.cash,12);for(let i=0;i<6;i++)u.click('buy',0);assert.equal(u.state.stock[0],6);u.click('buy',0);assert.equal(u.state.stock[0],6);u.click('remove',0);assert.equal(u.state.cash,7);assert.equal(u.focused.dataset.action,'remove');});
test('detached repeated button event cannot execute twice; repeated keyboard activation suppressed',()=>{const u=mount(),old=u.click('buy',0);u.listeners.click({target:old});assert.equal(u.state.stock[0],1);let prevented=false;u.listeners.keydown({repeat:true,key:'Enter',preventDefault(){prevented=true;}});assert.equal(prevented,true);});
test('controller transitions six nights to failure then retry resets seed and state',()=>{const u=mount();for(let i=0;i<6;i++){u.click('open');u.click('skip');u.click('skip');u.click('close');}assert.equal(u.state.phase,'done');assert.ok(u.html.includes('もう一夜、腕試し。'));assert.equal(u.buttons().length,2);const seed=u.state.seed;u.click('retry');assert.equal(u.state.cash,12);assert.equal(u.state.phase,'shop');assert.equal(u.state.seed,seed);assert.equal(u.focused.dataset.action,'open');});
test('controller reaches success via forecast-only planning, then creates a new seed',()=>{const u=mount();for(let i=0;i<6;i++){const plan=bestPlan(u.state);for(let g=0;g<3;g++)for(let n=0;n<plan.basket[g];n++)u.click('buy',g);u.click('open');for(let k=0;k<2;k++)u.click((plan.mask&(1<<k))?'serve':'skip');if(plan.invite){u.click('invite');u.click(E.canServe(u.state.stock,E.currentOrder(u.state))?'serve':'skip');}else u.click('close');}assert.equal(u.state.phase,'done');assert.ok(u.state.cash>=40);assert.ok(u.html.includes('夜市の名仕入れ番！'));const seed=u.state.seed;u.click('new');assert.notEqual(u.state.seed,seed);assert.equal(u.state.cash,12);});
test('controller mystery reveal, disabled sell, close and live status update',()=>{const u=mount();u.click('open');u.click('skip');u.click('skip');u.click('invite');assert.equal(u.state.phase,'late');assert.equal(u.state.cash,10);u.click('serve');assert.equal(u.state.phase,'late');u.click('skip');assert.equal(u.state.round,1);assert.ok(u.notice.textContent.includes('閉店'));});
