'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const root=require('node:path').join(__dirname,'..'),E=require(root+'/games/sky-plates/engine');
function boot(){let state,frame,clock=1;class Element{constructor(target){this.dataset={target};this.handlers={};this.disabled=false;this.hidden=false;this.textContent='';this.classList={add(){},remove(){},toggle(){}};}addEventListener(t,cb){(this.handlers[t]??=[]).push(cb);}setPointerCapture(){}fire(t,extra={}){const e={key:'',pointerId:1,preventDefault(){this.prevented=true;},target:this,...extra};for(const f of this.handlers[t]||[])f(e);return e;}}
const ids={};for(const id of ['world','pause','spin','overlay','heading','primary','description','restart','time','score','hint','spin0','spin1','spin2','spin3'])ids[id]=new Element();
const ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});ids.world.getContext=()=>ctx;
const controls=[0,1,2,3].map(x=>new Element(x)),win=new Element(),doc=new Element();doc.getElementById=id=>ids[id];doc.querySelectorAll=()=>controls;doc.hidden=false;
vm.runInNewContext(fs.readFileSync(root+'/games/sky-plates/game.js','utf8'),{SkyPlates:{...E,create(){state=E.create();return state;}},document:doc,window:win,requestAnimationFrame:cb=>frame=cb,Math});function tick(n=1){for(let i=0;i<n;i++){clock+=1000/60;frame(clock);}}tick();return{ids,controls,win,doc,tick,get state(){return state;}};}
test('controller full keyboard victory and retry resets input',()=>{const b=boot();b.ids.primary.fire('click');b.win.fire('keydown',{key:' '});while(b.state.status==='playing'){if(b.state.latched){b.win.fire('keyup',{key:' '});b.win.fire('keydown',{key:String((b.state.target+1)%4+1)});b.win.fire('keydown',{key:' '});}b.tick();}A.equal(b.state.status,'won');A.equal(b.ids.overlay.hidden,false);A.equal(b.ids.spin.disabled,true);b.ids.primary.fire('click');b.tick(60);A.equal(b.state.refills,0);A.equal(b.state.status,'playing');});
test('idle failure, pointer charge release/cancel, retry',()=>{const b=boot();b.ids.primary.fire('click');b.ids.spin.fire('pointerdown');b.tick(20);A.ok(b.state.charge>0);b.ids.spin.fire('pointercancel');b.tick();A.equal(b.state.charge,0);b.tick(1000);A.equal(b.state.status,'lost');b.ids.primary.fire('click');A.equal(b.state.tick,0);A.equal(b.state.score,0);});
test('blur/hidden pause freeze and explicit resume without stuck spin',()=>{for(const mode of ['blur','hidden']){const b=boot();b.ids.primary.fire('click');b.ids.spin.fire('pointerdown');b.tick(20);if(mode==='blur')b.win.fire('blur');else {b.doc.hidden=true;b.doc.fire('visibilitychange');}A.equal(b.state.status,'paused');const t=b.state.tick;b.tick(100);A.equal(b.state.tick,t);b.ids.primary.fire('click');b.tick(60);A.equal(b.state.status,'playing');A.equal(b.state.refills,0);}});
test('P repeat ignored; pause restart clean',()=>{const b=boot();b.ids.primary.fire('click');b.tick(20);b.win.fire('keydown',{key:'p'});b.win.fire('keydown',{key:'p',repeat:true});A.equal(b.state.status,'paused');b.ids.restart.fire('click');A.equal(b.state.tick,0);A.equal(b.state.status,'playing');});
test('Space remains native on ready/paused/result buttons',()=>{const b=boot();A.notEqual(b.win.fire('keydown',{key:' '}).prevented,true);b.ids.primary.fire('click');A.equal(b.win.fire('keydown',{key:' '}).prevented,true);b.win.fire('keyup',{key:' '});b.ids.pause.fire('click');A.notEqual(b.win.fire('keydown',{key:' '}).prevented,true);});
