'use strict';
(()=>{const E=SkyPlates,$=id=>document.getElementById(id),c=$('world'),ctx=c.getContext('2d'),buttons=[...document.querySelectorAll('[data-target]')];let s=E.create(),held=false,last=0,acc=0;
function clear(){held=false;s.charge=0;s.latched=false;$('spin').classList.remove('holding');}
function reset(){clear();s=E.create();E.start(s);acc=0;ui();}
function toggle(){clear();E.pause(s);ui();}
$('primary').addEventListener('click',()=>{if(s.status==='paused'){clear();E.pause(s);}else reset();ui();});$('restart').addEventListener('click',reset);$('pause').addEventListener('click',toggle);
buttons.forEach(b=>b.addEventListener('click',()=>{clear();E.target(s,+b.dataset.target);ui();}));
function release(){held=false;$('spin').classList.remove('holding');}
$('spin').addEventListener('pointerdown',e=>{e.preventDefault();if(s.status!=='playing')return;held=true;$('spin').classList.add('holding');try{$('spin').setPointerCapture(e.pointerId);}catch{}});
for(const e of ['pointerup','pointercancel','lostpointercapture','pointerleave'])$('spin').addEventListener(e,release);
window.addEventListener('keydown',e=>{if([' ','1','2','3','4','p','P','Escape'].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key==='p'||e.key==='P'||e.key==='Escape'){toggle();return;}if(s.status!=='playing')return;if('1234'.includes(e.key)&&e.key.length===1){clear();E.target(s,+e.key-1);}if(e.key===' '){held=true;$('spin').classList.add('holding');}});window.addEventListener('keyup',e=>{if(e.key===' ')release();});
function interrupt(){clear();if(s.status==='playing')E.pause(s);ui();}window.addEventListener('blur',interrupt);document.addEventListener('visibilitychange',()=>{if(document.hidden)interrupt();});
function ui(){const running=s.status==='playing';$('time').textContent=Math.max(0,E.DURATION-s.time).toFixed(1);$('score').textContent=s.score;$('pause').disabled=!running;$('spin').disabled=!running;buttons.forEach((b,i)=>{b.disabled=!running;$('spin'+i).textContent=Math.ceil(s.spin[i]);b.classList.toggle('active',s.target===i);b.classList.toggle('urgent',s.spin[i]<30);});$('overlay').hidden=running;$('restart').hidden=s.status!=='paused';if(s.status==='paused'){$('heading').textContent='ひと息つこう';$('description').textContent='お皿も時間も止まっています';$('primary').textContent='再開する';}if(s.status==='won'){$('heading').textContent='フィナーレ、大成功！';$('description').textContent=`4枚を守り切った！ 拍手 ${s.score} ／ 回し直し ${s.refills}回`;$('primary').textContent='もう一度挑戦';}if(s.status==='lost'){$('heading').textContent=`${s.lostPlate+1}番のお皿が落ちた！`;$('description').textContent='少ない回転と、移動距離を見比べてみよう';$('primary').textContent='もう一度挑戦';}if(running)$('hint').textContent=Math.abs(s.x-E.X[s.target])>.01?`${s.target+1}番へ移動中…`:s.latched?'回し終わり！ 指・Spaceを離そう':held?`回しています ${Math.round(s.charge/E.CHARGE*100)}%`:`${s.target+1}番の前。「回す」を長押し`;}
function line(x,y,X,Y,color,w=1){ctx.strokeStyle=color;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(X,Y);ctx.stroke();}function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function draw(){ctx.save();ctx.scale(2,2);let sky=ctx.createLinearGradient(0,0,0,350);sky.addColorStop(0,'#182640');sky.addColorStop(1,'#633c58');ctx.fillStyle=sky;ctx.fillRect(0,0,360,350);for(let i=0;i<30;i++){const x=(i*79+13)%360,y=(i*43+8)%160;ellipse(x,y,i%3===0?1.2:.6,1,'#fff0c0');}ellipse(290,48,24,24,'#ffe6b5');ellipse(300,40,23,23,'#23304a');for(let i=0;i<5;i++)ellipse(i*90-10,278+Math.sin(i)*9,70,23,'#aaa0c450');ctx.fillStyle='#9c4055';ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(55,50,18,188);ctx.lineTo(0,210);ctx.fill();ctx.beginPath();ctx.moveTo(360,0);ctx.quadraticCurveTo(305,50,342,188);ctx.lineTo(360,210);ctx.fill();line(0,8,360,8,'#f0bc71',3);for(let i=0;i<13;i++)ellipse(i*30,10,3,3,'#ffe8ac');ctx.fillStyle='#8c5555';ctx.fillRect(16,277,328,21);ctx.fillStyle='#e2ae71';ctx.fillRect(16,275,328,4);line(30,298,8,350,'#372640',7);line(330,298,352,350,'#372640',7);
const colors=['#7ed9d3','#f2b979','#b6a4ed','#ef8aa8'],g=E.gust(s);for(let i=0;i<4;i++){const x=E.X[i],danger=1-s.spin[i]/100,wobble=Math.sin(s.time*(6+danger*12)+i)*danger*.18;line(x,275,x,135,'#efc58d',4);ellipse(x,278,14,4,'#372541');ctx.save();ctx.translate(x,129);ctx.rotate(wobble);ellipse(0,0,30,7,colors[i]);ellipse(0,-2,22,3,'#ffffff60');ctx.restore();if(g===i){for(let k=0;k<3;k++)line(x-30,84+k*7,x+20,84+k*7,'#c3e1fb',1.3);}ctx.fillStyle='#fff3d8';ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillText(String(i+1),x,115);ctx.fillStyle='#20192e';ctx.fillRect(x-24,153,48,6);ctx.fillStyle=s.spin[i]<30?'#ff7c90':colors[i];ctx.fillRect(x-24,153,48*s.spin[i]/100,6);if(s.target===i){ctx.strokeStyle='#ffe5ac';ctx.lineWidth=2;ctx.strokeRect(x-28,166,56,3);}}
const x=s.x;ellipse(x,277,16,4,'#201a33');line(x-4,264,x-9,275,'#192b42',5);line(x+4,264,x+10,275,'#192b42',5);ctx.fillStyle='#f0b563';ctx.fillRect(x-9,236,18,30);ellipse(x,226,9,11,'#f1d4b3');ctx.fillStyle='#33243b';ctx.fillRect(x-11,214,22,5);ctx.fillRect(x-7,207,14,9);const lift=s.charge>0||s.latched;line(x-8,241,x-16, lift?224:255,'#f0b563',5);line(x+8,241,x+16,lift?222:255,'#f0b563',5);if(s.charge>0){ctx.strokeStyle='#a0e7d6';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,229,19,-Math.PI/2,-Math.PI/2+s.charge/E.CHARGE*Math.PI*2);ctx.stroke();}ctx.fillStyle='#fff1d2';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(g>=0?`風が ${g+1}番 に吹いている`:'回転が少ないお皿を見つけよう',180,324);ctx.restore();}
function frame(t){if(last){acc+=Math.min((t-last)/1000,.05);while(acc>=E.DT){E.step(s,held);acc-=E.DT;}}last=t;ui();draw();requestAnimationFrame(frame);}ui();requestAnimationFrame(frame);
})();
